# Generated by Django 5.0 on 2024-01-05 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0004_alter_workorderevent_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_entry', models.BooleanField(default=True)),
                ('work_order_pin_access', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='door_events', to='work_orders.workorder')),
            ],
        ),
    ]
