# Generated by Django 5.0 on 2024-01-06 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0005_doorevent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkOrderEvent',
        ),
    ]
